# In this directory, run the following command to build this builder.
# $ gcloud beta builds submit . --config=dev.cloudbuild.yaml --substitutions=_COMPOSER_NAME="vamp-airflow-staging-2",_COMPOSER_REGION="europe-west1",_DAGS_BUCKET="europe-west1-vamp-airflow-s-95799ec8-bucket"

steps:
  - name: 'gcr.io/cloud-builders/docker'
  id: collector_deploy_process
  entrypoint: 'docker'
  args: [
          'build',
          '--build-arg',
          'PROJECT_ID=${PROJECT_ID}',
          '--build-arg',
          '--tag=gcr.io/$PROJECT_ID/metrics-dashboard:${BUILD_ID}',
          '--file=Dockerfile_metrics_deployment_cloudbuild',
          '.'
        ]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/composer-staging/versions/latest
    env: 'COMPOSER_SECRETS'


timeout: 3600s #1 hour timeout accommodates the long running Composer upgrade operation

options:
  logging: CLOUD_LOGGING_ONLY
