# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=dev.cloudbuild.yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: metrics_build_process
    entrypoint: docker
    args: [
            'build',
            # '--build-arg',
            # 'METRICS_SECRETS=$${METRICS_SECRETS}',
            '-t','eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
            '-f','Dockerfile_metrics_deployment_cloudbuild',
            '.'
          ]
    # secretEnv: ['METRICS_SECRETS']

  - name: 'gcr.io/cloud-builders/docker'
    id: metrics_push_container_process
    args: ['push', 'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}']
    waitFor:
      - metrics_build_process

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: metrics_cloud_run_deploy_process
    entrypoint: gcloud
    args: [
      'run', 'deploy',
      'metrics-dashboard', '--image', 'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'FIXER_API_KEY=FIXER_API_KEY:latest,DEBUGMODE=_DEBUGMODE:latest,WHITELIST_EMAILS=_WHITELIST_EMAILS:latest,HOST=_HOST:latest,DATABASE=_DATABASE:latest,DBUSER=_DBUSER:latest,PASSWORD=_PASSWORD:latest,SSLMODE=_SSLMODE:latest,DEFAULT_S3_BUCKET=_DEFAULT_S3_BUCKET:latest,AWS_ACCESS_KEY=_AWS_ACCESS_KEY:latest,AWS_SECRET_ACCESS_KEY=_AWS_SECRET_ACCESS_KEY:latest,ANALYTICS_BUCKET=_ANALYTICS_BUCKET:latest,ANALYTICS_API_BASE=_ANALYTICS_API_BASE:latest,ANALYTICS_API_KEY=_ANALYTICS_API_KEY:latest',
      ]
    waitFor:
      - metrics_push_container_process
    # secretEnv: ['METRICS_SECRETS']

# availableSecrets:
#   secretManager:
#   - versionName: projects/703731371978/secrets/metrics-dashboard-dev/versions/latest
#     env: 'METRICS_SECRETS'



timeout: 1800s
images: [
  'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
]

options:
  logging: CLOUD_LOGGING_ONLY
