# In this directory, run the following command to build this builder.
# $ gcloud config set project vamp-metrics-prod
# $ gcloud builds submit . --config=prod.cloudbuild.yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: metrics_build_process
    entrypoint: docker
    args: [
            'build',
            '-t','eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
            '-f','Dockerfile',
            '.'
          ]

  - name: 'gcr.io/cloud-builders/docker'
    id: metrics_push_container_process
    args: ['push', 'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}']
    waitFor:
      - metrics_build_process

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: metrics_cloud_run_deploy_process
    entrypoint: gcloud
    args: [
      'run', 'deploy',
      'metrics-dashboard', '--image', 'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'FIXER_API_KEY=FIXER_API_KEY:latest,DEBUGMODE=DEBUGMODE:latest,WHITELIST_EMAILS=WHITELIST_EMAILS:latest,HOST=HOST:latest,DATABASE=DATABASE:latest,DBUSER=DBUSER:latest,PASSWORD=PASSWORD:latest,SSLMODE=SSLMODE:latest,DEFAULT_S3_BUCKET=DEFAULT_S3_BUCKET:latest,AWS_ACCESS_KEY=AWS_ACCESS_KEY:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,ANALYTICS_BUCKET=ANALYTICS_BUCKET:latest,ANALYTICS_API_BASE=ANALYTICS_API_BASE:latest,ANALYTICS_API_KEY=ANALYTICS_API_KEY:latest',
      ]
    waitFor:
      - metrics_push_container_process


timeout: 1800s
images: [
  'eu.gcr.io/$PROJECT_ID/vamp-analytics/metrics-dashboard:${BUILD_ID}',
]

options:
  logging: CLOUD_LOGGING_ONLY
